image: openjdk:8-jdk

variables:
  ANDROID_BUILD_TOOLS: "25.0.2"
  NDK_VERSION: "13b"

before_script:
  - cat /etc/issue
  - uname -a
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1 ant ant-optional faketime git tcl libtool automake autoconf gawk libssl-dev make
  - cd ..
  - wget --quiet --output-document=android-sdk.tgz https://dl.google.com/android/repository/tools_r25.2.5-linux.zip
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - unzip -qq -d $ANDROID_HOME android-sdk.tgz
  - echo y | $ANDROID_HOME/tools/android --silent update sdk --no-ui --all --filter
    android-9,platform-tools,extra-android-m2repository,build-tools-${ANDROID_BUILD_TOOLS}
  - export PATH=$PATH:${ANDROID_HOME}/platform-tools
  - wget --quiet --output-document=android-ndk.zip https://dl.google.com/android/repository/android-ndk-r${NDK_VERSION}-linux-x86_64.zip
  - unzip -qq android-ndk.zip
  - export ANDROID_NDK_HOME=$PWD/android-ndk-r${NDK_VERSION}

build:
  script:
    - cd $CI_PROJECT_DIR
    - ./make-release-build
